### ISSUE TITLE
on windows: relogin_claude always true， why open without cookies？

### ISSUE THREAD

**Issue by yangkang2021** [Databingo/aih#10]

**Comment by Databingo** [comment]
Hi, if you were already logged-in Claude.ai on your Chrome browser, it was opened with cookies .

However, the problem is that https://claude.ai has detected it as an unusual access, and response with "we are unable to serve you..." message.

Apologies for the inconvenience and I am continuing to investigate the issue. In the meantime,  please consider using alternative models such as Bard, chatGPT or HuggingChat instead to meet you needs.

**Comment by Databingo** [comment]
Hi, Claude now works well, please check release v0.1.6
