### ISSUE TITLE
bard json: cannot unmarshal array into Go value of type string

### ISSUE THREAD

**Issue by moisestohias** [Databingo/aih#2]
Bard now has an issue, when invoking it returns this error:
json: cannot unmarshal array into Go value of type string

**Comment by Databingo** [comment]
Hi, I used found this issue, when I make sure the internet access it work well.
Please try to figure out the internet accessiblity for bard, normally it require an American IP.
Feel free to feedback.
Thanks.

**Comment by moisestohias** [comment]
Can you provide information on what and how to use the proxy? cause when I use VPN it asks for a proxy.

**Comment by Databingo** [comment]
Sure. A proxy is a service that transports your HTTP/HTTPS requests and data to Google, for breaking blocks or showing a different IP.

Any kind of proxy service software has an entrance point with the protocol in front, for example `socks5://127.0.0.1:7890` with protocol `socks5` on local machine, or `https://101.227.97.240:443` with protocal `https` on remote machine.

In your case, you could set your proxy in two ways:

1. Set your VPN as a system proxy so that every single internet transaction on you PC would go through it.
2. Find out your VPN's entrance point and set it in Aih to use it as the proxy.

For example, suppose your VPN client software is ClashX. For the first method you can click **Set as system proxy**; For the second method, you could click **Copy shell command** to see `export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890` to figure out the `all_proxy` entrance is `socks5://127.0.0.1:7890`.
![Screenshot](https://user-images.githubusercontent.com/12667566/236124621-fd90b2cb-f8f2-49fc-b8cc-8555312f61b5.png)

Thanks and hope it's useful.
