### ISSUE TITLE
Add each AI parameter?

### ISSUE THREAD

**Issue by kwekewk** [Databingo/aih#4]
like reset in bard and Claude. System message, temperature for api mode

**Comment by Databingo** [comment]
Thanks, that's a good idea. For now, it's useful for ordinary, fast, rush, emergency usage. I haven't stepped into such details yet. I am considering whether it's worth devoting proper effort to developing those features.

**Comment by kwekewk** [comment]
I think there aren't many projects that combine multiple AI. Aih is easier to set up and use. Maybe we should start with adding option to use gpt-4 API?

**Comment by Databingo** [comment]
Yes, good Idea. May be add `.chatapi4` command? There are 4 chosens for 8K+Prompt, 8K+Completion, 32K+Prompt and 32K+Compeltion. I wonder how to keep commands as simple as possible?

**Comment by Databingo** [comment]
The new command `.price` has been added, and the new binaries have been uploaded concurrently. It appears to be an elegant solution for simplicity. 
![price](https://github.com/Databingo/aih/assets/12667566/bc0e1947-11d8-454c-bbde-258e70637c84)
Please check it & do not hesitate to give valuable suggestions.
Thank you.

**Comment by kwekewk** [comment]
it seems bug, not switching to gpt api? maybe combine with .chatapi and prompted selection like above instead?

![image](https://github.com/Databingo/aih/assets/101484315/fe86fdec-3ac2-41df-8d77-531e72291f8f)

**Comment by Databingo** [comment]
Thank you!
Fixed in new uploaded binaries with auto switching to` .chatapi`.
![price-](https://github.com/Databingo/aih/assets/12667566/d6840752-664b-44f1-8f19-a7233f41f54e)

Yes, combining selection with `.chatapi` is a good idea, but it will trigger prompted selection everytime when user type `.chatapi`. It seems `.price` as a separated configuration sub-command better. 
Another reason is that `.chatapi` will run into the exist conversation without reopening a new one with the selection.
Please testing and feel free to give valuable suggestions.

**Comment by Databingo** [comment]
Please note that the `.price` command has been changed to `.chatapi.`, but `.price` can still be used for compatibility purpose.
This is because `.chatapi.` could establish a uniform style like `.chatapi.` as the configuration parameter setting of `.chatapi` then `.bing.` for `.bing`, `.bard.` for `.bard`, etc.
Hope the setup and usage process is easy for users.
Very appreciate your valuable suggestions.
Thank you.

**Comment by kwekewk** [comment]
Hi, i have new suggestion. i wonder we can use / command like autocompletion or simplify all selection under .chat and .key . Next maybe export/save chat feature  would be good.

Chat-related:
.chat - ChatGPT Web (free)
.chatapi - ChatGPT Api (pay)
.chatapi. - Set ChatGPT API mode such as GPT3Dot5Turbo(default), GPT4, GPT432K
-gpt-3.5-turbo, $0.002/1K tokens
-gpt-4 8K Prompt, $0.03/1K tokens
-gpt-4 8K Completion, $0.06/1K tokens
-gpt-4 32K Prompt, $0.06/1K tokens
-gpt-4 32K Completion, $0.12/1K tokens
.bard - Google Bard (in chat)
.bing - Bing Chat (in chat)
.claude - Claude (via Slack) (in chat)
Key-related:
.bardkey - Reset Google Bard cookie
.bingkey - Reset Bing Chat coolie
.chatkey - Reset ChatGPT Web accessToken
.chatapikey - Reset ChatGPT Api key
.claudekey - Reset Claude Slack keys

**Comment by Databingo** [comment]
Hi, insightful advice & should be holistically considered for the benefits of potential users who are dwelling in terminal and seek to intentionally combine the logical power of artificial intelligence.

**Comment by Databingo** [comment]
Hello there! I have made an improvement according to your advice. 
1. All the mode related commands such as `.bard`, `.bing` etc. were simplified to an `/` command.
2. Now the `.bardkey`,`.bingkey`,`.chatkey`,`.chatapikey`, `.claudekey` are all integrated into a single command: `.key`. 
3. A new file `history.txt` will persist all the conversations locally.
4. New hotkeys `j`, `k`, `g`, `G`, `q`, `Enter` were added for seamless scrolling through lengthy response text & history.

Very appreciate your insightful suggestions, now `/` and `.key` command could accomodate and manage any new emerging modes in the future.
Hope these upgrades fit for the convenience of valuable users.
Thanks.
