### ISSUE TITLE
Bard AI is not working with a json unmarshall error

### ISSUE THREAD

**Issue by keanliu** [Databingo/aih#7]
![image](https://github.com/Databingo/aih/assets/42489038/0592ccf7-7159-43a8-b638-5f8fec65c9a0)

I think the error is something about "json: cannot unmarshal string into Go value of type []interface {}", in the bard module, 

It originally works ok, but someday, it fail to work, I tried the latest version, still don't work.

My go version is 1.20.

Thanks for your effort.

**Comment by Databingo** [comment]
Hi there, thanks for using Aih!

1.Error `"json: cannot unmarshal string into Go value of type []interface {}"` normally caused by the returned empty [[][][]] data which means the server did not return validated response.

2.For now the `SNlM0e` value lost so making the requesting not work.

3.You could try the newest version of Aih which employ the `undetected_chromedriver` to interact with google server.

4.You may need `python3` and  `pip3` installed and run `pip3 install undetected_chromedriver`.

5.When you run Aih need input bard cookie and wait a while time for `bard` headless browser login and initialize by return "Bard initializing..." on terminal until it prepared well.

Please do not hesitate to push more question, thanks a lot!

**Comment by keanliu** [comment]
I have tried latest version, but got following error after setting cookie:
![image](https://github.com/Databingo/aih/assets/42489038/f519b134-c130-4214-80bd-f568b67012c2)

the 'undetected_chromedriver' was already installed.

1. Although it is not working in my env, seems you have bring the interactive input/output back (instead of showing the output in a seperated screen), I like this.
2. I think you can add a 'logging' mechanism, so if there is problem, it is easier to identify the problem.

Thanks for your effort, the tool is very useful.

**Comment by Databingo** [comment]
Hi there!
Nice to receive feedback from you.
If you check the code you could figure out that `Invalid cookie` indicate a short cookie that seems not a valid google login cookie.
![Screen Shot 2023-06-14 at 11 34 31 AM](https://github.com/Databingo/aih/assets/12667566/4a453562-b7a3-4b05-9331-8ffd2d206533)
In my case, an effective bard login cookie seems like this:
![Screen Shot 2023-06-14 at 11 40 20 AM](https://github.com/Databingo/aih/assets/12667566/3745020c-5e90-49a0-bb6f-4981fc1e7975)
Please make sure you are using a right login cookie of google bard from the certain page of "www.bard.google.com".
If it still not work properly, welcome to feedback!

Thanks for your testing.

**Comment by keanliu** [comment]
Still, I was not able to have it work

![image](https://github.com/Databingo/aih/assets/42489038/6bf88cec-0601-47d5-9a0f-72d6a83d7e2b)

Seems this need Chrome being installed, I have it installed. 

I don't know why.

Thanks for your effort.

**Comment by Databingo** [comment]
Hi! 
It indeed needs chrome be installed.
And it needs time to initialize.
Firstly, you need a valid cookie input via `.key` command.
Secondly please be a little patient for the initializing process by keep typing "hello" to see "Bard initializing..." untill Aih give you a google bard response string.
